os: Visual Studio 2015

environment:
  matrix:
  - QT: C:\Qt\5.7\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

build_script:
  - (robocopy /e C:\OpenSSL-Win64 openssl) ^& IF %ERRORLEVEL% LEQ 1 exit 0
  - call "build_windows.cmd"
