os: Visual Studio 2015

environment:
  matrix:
  - COMPILER: mingw32
  - COMPILER: msvc2013_32
  - COMPILER: msvc2013_64

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

install:
  - if [%COMPILER%]==[msvc2013_64] ( xcopy /E /I C:\OpenSSL-Win64 openssl )
    else ( xcopy /E /I C:\OpenSSL-Win32 openssl )

build_script:
  - call build_windows.bat %COMPILER%
