os: Visual Studio 2015

environment:
  matrix:
  - COMPILER: mingw32
  - COMPILER: msvc2013_32

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

build_script:
  - xcopy /E /I C:\OpenSSL-Win32 openssl
  - call build_windows.cmd %COMPILER%
